sudo: true
language: node_js
node_js:
- lts/*
cache:
- node_modules
services:
- mongodb
- docker
env:
  global:
  - secure: jVv6GoeiP/KzY5RCfvK20r8qf/CuSQDLbc36hThoDLEHsQ06DS4hvqKr0wnHj3jrx/ZxA8LQgbW7AHRhm7PbQLog0seAIQ04u3bAP7s67px5vQH1LWY9C6E6xII8/Pvac1yH66HvGvQISe0nN3afGDpP4WAbuxlJgpCgN1AaL5pSt37x5WkLNPdxWY8ca4aAUUwNoQvMHWMse9liSkarb7yVN0d/yMVVTpiJqFm5DqrH8E/VNXapD8+r2sw/UWcdSiZe0AEnpG70EKuu2eLbUgE0p63ZVQU+zLwnWnn6yzIz9zCmgIdw/OCJtvBiZSowvb4KE95H/nim+XclpzQeVPU4RuTOgcVvUsT0SThaDuZ6gzwM3Se+AEh/rsHgZxaNQXNj35iLsg+nWmVLy+sMIIe5nzaH0p8Sbh3d2Pm/ytB0FS4OWI/aRdXj9Nw/PiX4/0ISKv/6MsS4HmWgv7GBFLL6xeEDAFhk83vkXDHLURjihotvjZRQ2Rety007aGgN4q2I4apeV2YsUhetQlWKaPoTSveFz6y+VyZd7xVoVGUBYaDQqUy57u8tfEMG+OdpSXXqDRif3c2qdCRpMW0xbDppxfZGjMJ6h33x0VcjUmczvB4bFJiVNXwBx3DDa614qvvCFiyVQlPdH9H3YODEcNstte7sq/a6bch1aeBYJ7g=
  - secure: lgt7puNJwO52ujYnBVEA+7VPhK/UPfsXCJkjdKF3MB0nuxtHuBt8HaS8IlaY9+qYBtqCMlXEdy+YnpSHozCntG5a1OlLNH1akftAVmR4j5/ZLZRhud7RI9sWKn9iI9M2nC6iGkzh+e26x4Q1AIPcooTSQ4OqI4vvzxRZTqU4X0jEoxSl+wzHXHdFj5q5mXvxXbMLrdYraivQ2Asn+8lby2HrmWmRB9Hgb1+RrRN54wq2FWl1erjZov4SqADTD5wn7/K5bnIPP0csm/ffJNADaOx6trrqHqqCB7mjJ2K03Hy7r9L2742mlLRayBvEdsaaSpm/Grq7EFVi66arB9KXYQxGj7Ad/iRiTLl+Im+N7bbSVqn2GE2e1SCTuIisgtYBQrYXH90se6o/kSdtuo2/MHcR0BJjoIcPsQl1XbmQ1PTiOWJyihgiib1tIM1liAt1zdOZrEszgat7NFOpkcutas0M5YozY00nRs6rzMJQBm4UD7YBwmOmGmxKes8iKeQ7D5MU6Y9DYlDDJNBUrdgwhCN4AfP0PY0oIkfHQRf95BE8NhW4CFhP+Kr08+HDPwMchbOhx1dWXt/g9lWRy/GA/Prz53d5+gI6kwq7T2DbinkunTMle9LsSpaK5VB42q/J3mPiwN2NS6fJnzLEHVoUY7ZmqnXDoKnd8Xxx307sY3U=
  - secure: kCuuyDwSXlNL+yDSm7R353Cun26bSDrMlf9y5yk0VB4HZ1fBiUMLdn0i/n9LR73y5WhKER+ceH1HHW7GkQvORO9Cwd7hOtgOQRnfaZeHJ8ttDfUuOGGY2LaxHO85lRkm/Y4c5oHPVEMRDbYMGbAxWsMmXYlo26WJutEdnYlI5zZ0LOqzxWdvktQ2DvFvkbRDSjOA4+rx5uVoVvgoL7kwhvGURWlsAO4Gamt+KTEJZRceYOTH4JZf/Mv4+qH4dkg4xUyDafz7UO2mYis6ktbwRk994mdedPC0shZZmXTyaX9jTfAWjpbnsPYRGmKlXq6NCAGL/2isWgmtAr4KDipAVFCZSxUzdqw7JOWaNz0/zyXNvBckridLhxaIUS/964XKb7tWcQj5PdMSlYVowRfulsYEh47bbLAFVneM5qtcT57SgRcdXbF0065yDcQKJFjoAeQANQp9h6AymgbRu27kk6k44A+EqycgXVK3BUnsX+hb1lgFQsDlk6GctmM6rp2TGwfPUjzymF5mDdUV2f7IH72UjYisCcK/FyQ3JFlxE66lAsBO1iqSsdDn/waJ3Q8NBFe3ZUiebtkvi3S0Z/pxaH44A05D9aUKO4zrGYYh60Z2nvHoVz66PmXbd0udpDi8Lj64evjaoAeE34haI4gDq9At4AjVOIDvDkKEWeu/2sE=
  - MONGODB_URI=mongodb://127.0.0.1:27017/todos
  - PORT=8080
install:
- npm install
script:
- npm test
before_deploy:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker build -t todo-api .
- docker images
- docker tag todo-app $DOCKER_USERNAME/todo-api
deploy:
  provider: script
  script: docker push $DOCKER_USERNAME/todo-api
