sudo: true
language: node_js
node_js:
- lts/*
cache:
- node_modules
services:
- mongodb
- docker
env:
  global:
  - secure: "R5/Irr6q0Cq0z7Z0KEMKk+Fa73JHk4VTXDo3XahNuDyEnx30Ij9MR+v7df4og5ux+tBhQdA1gpnSUu5PdRH7jCo1qaon0oDnhgIElRjUyq8nlaUNMRu6f9Zy8z0KcdmV8h3LxkOWvxr5zhSPLLrNyCJug7rwWYagm+T+t2zthGtIW7pB5Yqi6aoAHhaGFgVAxNimrHjkdyZxcTeqKdqUIDH0ta7ET9kZdxqo8f4UqY1vmIBDlMu3UQV79Os/0iiD76/8jOeUW8O9f4IJbH/g4eazWmPPAOjEJFbH7gNKUxurE9RGCe5+C8PL3slU1dBM80xEi6pHOWNgv4X3YmprkSbArR/yw1u4DDHeVyoiM1YAQYIB69h7v0JrR3eYQ/G35m1DQ1HGBPzEUUTiZYDkNwxbFGtMyEbqyUT2iTjfiQNM31JUEqZOzHlKLpBGwwItPYEXm95Y6xGpqkO63dnd35LD9BzOzYKDlXS3JK3AAb8UMTq+m6qtf4WU44526Iq88cKlqhM0jRQ0OgnnjXzKdHmU9RD0HXyE2Ph/grxeEXSYi0rBrpnL71KbxZhUdgYVXvzuFyViSf0Ca12+5Alc9U7fprFyzm1G3Ke1ccZ7Y/97+Of/fa2QS5czc+CG0XNCmrOFw//iK1OK9DGEjP2nGhZC0WWwdsD6e8ROajxI4Yg="
  - secure: "b1w5GxnL0Z/vaMNT2z3uuoGvXKtNyhB7idBQqkMwXu+7EEZh/86PUlo7bKRYTD97VuXLn4P+VulvAdrwz+PQDyv/236gF3odh+c5Bvnz/bVIgjB87+lsewGiNtcWjrF1CwtLdJyLnFsI3MqTxcuFBaWIRRUom8tzWB6u0qU7AnmmXX2R1mwF22cx+42fUeEsZyNGu4hn+N33pR2ZFpYU/Eq33NAbbnQ70YNKrM4S7VQvMrIiJpobqXOPKF+8/NHsyOz9sRPRPdr55lXaa5LzbWs7hzr+py69hVHerKWO3lO+O3jE0jmoBmQw5f7bhBq8BIrZutF8sWURRnvKn+zK4LE+R9EW+rvegWVzO6nJAc/68fVlYTbbhKtWp71DFEbgRrnQDSh9BJMDivN3b7s6JsI4LMfS5Dr056TeLTnQT+U0ISlnlP/BHHPoR4W5a8Iih4hcNmmWcLHrpBEthxLnAOrwp+KlIuJh6WHWOcRczw4y/qTtpXzFoXC2JvLBYojJ/FM2W/ugFeargcIHw5Wgm4Qz4BDFgntIxLRv5fjfbTlwYuSx+lOE+WVsSQyYpAHjn+ZbLtpULlHQ7LuDsXYgTAvNDP+OErgCUO6O42V0BcNxitIbTpWjFja6BsrMrYTzVZFKo42+9uPLsJzMF10qLqz8i89CWCao23Ic8ThtMZM="
  - secure: "kCuuyDwSXlNL+yDSm7R353Cun26bSDrMlf9y5yk0VB4HZ1fBiUMLdn0i/n9LR73y5WhKER+ceH1HHW7GkQvORO9Cwd7hOtgOQRnfaZeHJ8ttDfUuOGGY2LaxHO85lRkm/Y4c5oHPVEMRDbYMGbAxWsMmXYlo26WJutEdnYlI5zZ0LOqzxWdvktQ2DvFvkbRDSjOA4+rx5uVoVvgoL7kwhvGURWlsAO4Gamt+KTEJZRceYOTH4JZf/Mv4+qH4dkg4xUyDafz7UO2mYis6ktbwRk994mdedPC0shZZmXTyaX9jTfAWjpbnsPYRGmKlXq6NCAGL/2isWgmtAr4KDipAVFCZSxUzdqw7JOWaNz0/zyXNvBckridLhxaIUS/964XKb7tWcQj5PdMSlYVowRfulsYEh47bbLAFVneM5qtcT57SgRcdXbF0065yDcQKJFjoAeQANQp9h6AymgbRu27kk6k44A+EqycgXVK3BUnsX+hb1lgFQsDlk6GctmM6rp2TGwfPUjzymF5mDdUV2f7IH72UjYisCcK/FyQ3JFlxE66lAsBO1iqSsdDn/waJ3Q8NBFe3ZUiebtkvi3S0Z/pxaH44A05D9aUKO4zrGYYh60Z2nvHoVz66PmXbd0udpDi8Lj64evjaoAeE34haI4gDq9At4AjVOIDvDkKEWeu/2sE="
  - MONGODB_URI=mongodb://127.0.0.1:27017/todos
  - PORT=8080
install:
- npm install
script:
- npm test
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t todo-app .
  - docker images
  - docker tag todo-app $DOCKER_USERNAME/todo-app
deploy:
  provider: script
  script: docker push $DOCKER_USERNAME/todo-app