sudo: true
language: node_js
node_js:
- lts/*
cache:
- node_modules
services:
- mongodb
- docker
env:
  global:
  - secure: "JrHx5BdDrjAvo55xa5cnxFE+crUHH6eblXvTD08CPWt3RU8OlV60EZFAhPeEMxNIvE8Q8bNtcIIbpGN5rnNevggcaqWS5wcOu/w1p3f7ZnFemNksYKH2ykvWbKByOJ8qxuRyws16IfMJ9fGz/tuIrdQpIVtopZBRIg92d1hXWjGpvv5JH+ABfRndHdoILIk8ilKwwc1cCImi8UGoW1/DSXE87YXiCx0AMOUhhnG5w5O2kYOnYCHKbw1oLJkdlpgGjZ0nL+EbcjaHb3MQ+wE8kRymNrYcgLFfW+S+hNZIdouaq2q4VEXIYdgGaONYwDaum08BnnzU+xtI/iaho7jRNrJCCCHVxvvFtmmpvtU0XsFiTKjeSSHT6Ncgh+ue8mQGM1O3//xboo52yu/AzI7SRC22dAbwn0kg0x7e3eZPUQzqRWuk2/n3U5uqr6pQrfNKp0a4x7Wefnvwj+ISeGwj6aXhYNwBlBL4v4i0ze73tzQcGlNf4TbnFi7GDqF9WYqBnbNecbMwREcfmbP/hdhmlH7qbpwLGSdGvID282/aA75NXriC1D8htHwVAjScmIfWUo+RCEZYwKk+7GXHzWt8CbxFSdIYNWkkXUkO6EfrN+P8mGBUv/0SGF0In7nNZF0q0F5cfb1oJ/so5eb2HAIfy/CejhL4rGJnbib02Sas8Gs="
  - secure: "JaWKn1ZlpWu5+AgZk7a6bj3lXyZ4WGCHnCpC/ixH6/qqIRvZz1aE49qGLo6MUtgqY8OilwGI3r6ZIUr/eTlbNCB8MqOpHExMgzDlmJN4h969VYerLKlVzdpvLP6DKewWjILLtbMK/qrWXFbXMx+bUkl7TIQEUHXeAl6wjlHQXJt8cVLF8ihS2tpiAB7/x5zjEAUHoN5VbB3p7wlbB+xhNp/7OsdGS93IGpY4RlKtcEMqE0mhOeaUOmAiOhpgXfyhwHqg/spBEdJT4uWzaWd+1sng/2ZqO6Gge1nXn7+Cuz5Gneb0BGq4c7DhULRbtKyYmWq9eACVYdpegb0z+JJXXgZA2JJP2RBpCgZfpXTe9vgTdlxyUN+5x+w66uICBVXZMFNjRc5/BntcPuEpylov9oJ/CQE+qLW5A3I9LfUMt5cMvoB6+O7Ds7SN+5EneWIk2NmmHA1yrDGoRZP3bZTstW6wxl2vsDYmhpuh1BuBnrdy8vMDN4X0JCgBK+klMDJ7XsNbsK22feGmMIzj1iBt7lTFQ2Sr1ZjAJmdVKPgguvcUF/GPEWz92gKgoLY/MNu2s9vXWTmi1Uti+tq13smGszT/t/z+1M5pDL28bXoSu4EROWVAzKk/69eZMYBDja3U6MQstec9lSSpN55O5Vra0d923NAbKiFxKufqDJod/qI="
  - MONGODB_URI=mongodb://127.0.0.1:27017/todos
  - PORT=8080
install:
- npm install
script:
- npm test
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t todo-app .
  - docker images
  - docker tag todo-app $DOCKER_USERNAME/todo-app
deploy:
  provider: script
  script: docker push $DOCKER_USERNAME/todo-app