sudo: false
language: node_js
node_js:
- lts/*
cache:
- node_modules
services:
- mongodb
install:
- npm install
script:
- npm run build
- npm test
deploy:
  provider: heroku
  api_key:
    secure: hvFo1ovQYLNkDP1emX2FHI37pk8pVjsgeuMawgi3Ei41DoDP2uuJrskAUKB9Z28ZQH0uFz/AKNqc8wcO/jU5esrLTxR6BSioO/0SoUcV4uPMGwssw4xD/PfX3u1ktuwMoG/Rk8nSNUnZefV/sRQ2F1xBSeeUKXsE4IQYzQTAXkayElNhAbzwZzWSNZzZbS7ng1PKiWYajR3pAroJILUFUWgHqjIAhDONK54zxGbogFwbnudRVOQ+FG1KYFbfo7VJ1mbBslMAjtizIlL53FHOvCNDG9OlDZ5DAolP/D5ObHwM6wxBQOfT99iw5pVi1lgn7VTYtaBu8z0RRtafW/KX2mR/e1Q+uAKEBrQ7q8BRKeMZCpLqswmlpN1IIQhXgSw+2JTNHY5yKfjnhX9Frbx4M1NX0xwrxOr2fbzkLVGTIQQ3kNjS7ln4e3x9eQo/U1LMT0GZ1f0US9iV/hyGizB2h2CSOE0VdZugAGG+HGpBFi6mo/81kDqr7E7Ui/GF/RQGMfwc4MGckIM1f4jNUK8748Zmwo0trNnER1cfDFzveX/vWAd5VsZusvp2Mw0X0gajPtIsdlqzs6c4Gaxg38xQpOBtNqtr9wnO/5KjucU5YqX0nKBsblUgPNMxxOZqv9nXxHqqv8IBZoYQkp0qSR1zwVRJR6pcIW61SBr7c3Wywe4=
  app: coding-domain
  skip_cleanup: true
  on:
    repo: SlimeDevs/task-manager
env:
  global:
  - secure: gK7IBjSlWnsatPjBzwCE0fei+3wflFAljolb20WYonfquROk9RIOXPcsixFbRfoGDF4QfFFDgzroyvJAnUTQ+5JhUWc9PUFS4YUqC1NMEL93nxYlDBJVPD3opxbvaUfP2z6RTJ/tJXFslkrX/Yz0C4venOM3QUlmAwS+WO1EUSqVw9qqVEgJlH7RHDFgshGSXK0Z4+6WtuDQrIdVMbyw39PtDK23FwRigRqvDLF60ThFW7TO3Ebb+//H0R0j5OyRU4W+QN7YiidS91p80LwHnvk5CQ2StKlK13soSVVk5nOEV/lo+NR263NVEtjXYSbibjA5ZTjmIoC4eSEhYU/7Kz2uG4r0rabIQmi58V3aiu8BTAqv/7QAs0jOu7w1nrizi5+0jPazWX1XsePnBJ+bojHEmRIqNsj+K5MUsVFRy/hJBulguXfSsO/Az/UOYqTrxQQ9OqL5S8Pcg65o3B+U6buUvY8/JhrVKtwIyM+wMHCtxHqC1IVYXlYMmk6h2y2K9CaKkeNDqO5ti+GykOzBtzdohkFNmbnO4/D+T6z+JehviKycEH1mpsc/gEXTmnwmbyEvs9rPx9UxORVhVf5tqjE+EPBzBc9gYoWB7pv7Fd73rnV3XPgUGluKkX39lS3Bq80MKyP8ScdgUhOpMAV57YAfAyvR/bOgkObtQYrR9Fo=
  - PORT_TEST=3000
  - MONGODB_URI_TEST=mongodb://127.0.0.1/task-manager-build
